# Generated by Django 4.1.3 on 2022-12-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
