# Generated by Django 4.1.3 on 2022-12-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avalicao',
            field=models.CharField(choices=[('P', 'Pessimo'), ('R', 'Ruim'), ('B', 'Bom'), ('M', 'Muito Bom'), ('O', 'Otimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
